{% set name = "occwl" %}
{% set version = "3.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../..

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt "

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - pythonocc-core =7.8.1
    - numpy
    - pyqt >=5
    - wxpython >=4
    - pyside2 >=5
    - pydeprecate
    - networkx
    - matplotlib
    - ipykernel
    - jupyter
    - ipython
    - pythreejs



test:
  source_files:
    - tests
  commands:
    - python -m unittest tests

about:
  home: https://github.com/AutodeskAILab/occwl
  license: BSD
  license_family: BSD
  summary: Lightweight Pythonic wrapper around pythonocc
  description: |
    OCCWL is a simple, lightweight Pythonic wrapper 
    around pythonocc (python bindings for OpenCascade).
