site_name: OCC Wrapper Library (occwl)
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python

setup_commands:
  - import sys; sys.path.insert(0, "src")

nav:
  - Home: index.md
  - API Documentation: api.md
  - Developers Guide: occwl_developers_guide.md